plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.glazero.ijkplayer'
    compileSdk 35

    defaultConfig {
        minSdk 21

        externalNativeBuild{
            cmake {
                cppFlags "-std=c++11"
//                abiFilters "arm64-v8a","armeabi-v7a","x86_64","x86"
                abiFilters "arm64-v8a","armeabi-v7a"
            }
        }
        targetSdk 35
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild{
        cmake{
            path  ("src/main/cpp/CMakeLists.txt")
        }
    }
}

dependencies {
    compileOnly 'androidx.appcompat:appcompat:1.7.0'
    compileOnly 'com.google.android.material:material:1.12.0'
}

afterEvaluate {
    // 注意，需要先执行assemble再执行publish
    // Android 编译后带 debug_info 的 so 库位置：build/intermediates/stripped_native_libs
    def _groupId = "com.glazero.iot"
    def _artifactId = "sdk-player"
    def _versionName = "1.0.1"
    def _versionCode = "1003"

    publishing {
        publications {
            release(MavenPublication) {
                groupId = _groupId
                artifactId = _artifactId
                version = _versionName
                artifact("$buildDir/outputs/aar/ijkplayer-cmake-release.aar")
            }
            debug(MavenPublication) {
                groupId = _groupId
                artifactId = _artifactId
                version = "${_versionName}.${_versionCode}-SNAPSHOT"
                artifact("$buildDir/outputs/aar/ijkplayer-cmake-debug.aar")
            }
        }
        repositories {
            maven {
                def isRelease = false
                def taskNames = project.gradle.startParameter.taskNames
                if (!taskNames.isEmpty()) {
                    isRelease = taskNames.first().contains("Release")
                }
                url = isRelease ?
                        uri("https://packages.aliyun.com/maven/repository/2075287-release-uz6THy/") :
                        uri("https://packages.aliyun.com/maven/repository/2075287-snapshot-INVkYp/")

                credentials {
                    username = "601fc638f79db5b68adfc6ae"
                    password = "HIHsMOkuZVte"
                }
            }
        }
    }
}